### ISSUE TITLE
Feature: User can see their location on a map

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can pinpoint their position on a map

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

![image](https://user-images.githubusercontent.com/103610490/181379495-b12ebb73-dbc9-47d1-9295-01255447d7be.png)
![image](https://user-images.githubusercontent.com/103610490/181379544-e8a56d7a-194b-4dc8-9001-b33b8b06f192.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to render google maps api
- [x] Create a component to get users's current Position
- [x] Update component to render a marker on user's current Position

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
