### ISSUE TITLE
Feature: User can view all stores near them on a map

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/final-project#2]
## ⚙️ Feature

User can view all store markers

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On a map, user will be able to see markers for every store around them

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103610490/181382816-828fa14d-f975-498f-915c-df9426ea751f.png)
![image](https://user-images.githubusercontent.com/103610490/181382856-8c20f8b7-4d69-42a4-a8de-784e176d6328.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.
### ☁️ Server Tasks

- [x] Update `server/index.js` to handle yelp requests with yelp fusion package

### ⚡ Client Tasks

- [x] Create a component to render markers based on store lat and long
- [x] Update component to fetch from server yelp object of stores and store the object into state
- [x] Update map component to use render marker component

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
