### ISSUE TITLE
Feature: User can filter types of stores

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter types of stores

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can input search categories to find stores related to the category around the user's position

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/103610490/181383551-739154d4-fd70-4cc2-9fc7-f520fb7db08d.png)
![image](https://user-images.githubusercontent.com/103610490/181383634-220e46d0-2bc5-40a3-9a52-ee98991b64e7.png)
![image](https://user-images.githubusercontent.com/103610490/181383661-3b763613-70dc-4a38-b631-dcbc41211eee.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to get request from yelp with user filtered categories
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a class component to render toolbar
- [x] Add a component for user category search input in toolbar class component
- [x] Update map component to send fetch get request with user input category as a parameter

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
