### ISSUE TITLE
Feature: User can view details of a store

### ISSUE THREAD

**Issue by tychiang922** [tychiang922/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view details of a store

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After clicking a store marker, users can view specific details of that store including hours, price, pictures, and reviews

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103610490/181384258-1259d047-8731-47ae-b33f-a9b0f7e48c46.png)
![image](https://user-images.githubusercontent.com/103610490/181384311-7a4076c5-7ca4-4d04-8cc9-f783914bdddd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to get details of a store from yelp based on store id
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to handle click events on map markers
- [ ] Update navbar component to fetch details of a store on marker click
- [ ] Update navbar component to display details of store after fetch completes

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
